mode: asr
residual: True
data:
  dataset:
    name: coco
    dataset_root: /media/exx/HDD/zhenyulu/data/coco
    clip_image_transform: ViT-L/14 #ViT-B/32 #ViT-L/14
    split_prefix: SpokenCOCO_ksplit
    load_image: true
    load_audio: true
    tokenizeText: true
    modalities: ["audio", "image", "text"]
  batch_size: 2
  dev_batch_size: 2
  split_ratio: 0.9

ASR:
  type: Whisper
  name: base.en

